In [34]:
true_path = '../../../DATASETS/fold1/metrics/masks_fold1.npy'
true_tissue_path = '../../../DATASETS/fold1/metrics/types_fold1.npy'

pred_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold3Tr_fold2Val_amp/net_epoch49/RTS_softmax/hor_ver_rot90_90_mult_gauNoi_gauBlur/masks_fold1.npy'
save_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold3Tr_fold2Val_amp/net_epoch49/RTS_softmax/hor_ver_rot90_90_mult_gauNoi_gauBlur/'

In [34]:
true_path = '../../../DATASETS/fold3/metrics/masks_fold3.npy'
true_tissue_path = '../../../DATASETS/fold3/metrics/types_fold3.npy'

pred_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold1Tr_fold2Val_amp/net_epoch48/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/masks_fold3.npy'
save_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold1Tr_fold2Val_amp/net_epoch48/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/'

In [40]:
true_path = '../../../DATASETS/fold3/metrics/masks_fold3.npy'
true_tissue_path = '../../../DATASETS/fold3/metrics/types_fold3.npy'

pred_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold2Tr_fold1Val_amp/net_epoch41/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/masks_fold3.npy'
save_path = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold2Tr_fold1Val_amp/net_epoch41/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/'

In [41]:
! python run.py --true_path={true_path} --pred_path={pred_path} --save_path={save_path} --type_path={true_tissue_path}

arguments extracted! 
all loaded!

 0
pq  0.5802540991381238
pq  0.5183540958919667

 1
pq  0.6191992230330995
pq  0.8791200000008792
pq  0.0

 2
pq  0.6344539591108523
pq  0.5554193953570342
pq  0.09796228448285661

 3
pq  0.6712469588704578
pq  0.0

 4
pq  0.5938970896020603
pq  0.0

 5
pq  0.615564324432994
pq  0.8841192875545323
pq  0.32535770317339435

 6
pq  0.7192516864781988
pq  0.0
pq  0.32897163364518883

 7
pq  0.7479581837220649
pq  0.3727269000003728

 8
pq  0.6889151509530625
pq  0.25095560583966703

 9
pq  0.6313459470204988
pq  0.8477119944446564

 10
pq  0.7297978036071389
pq  0.0
pq  0.8440201281635942

 11
pq  0.7972949058146299
pq  0.0

 12
pq  0.0
pq  0.41232186255965403

 13
pq  0.8754950607573383
pq  0.0

 14
pq  0.7116302537380274
pq  0.0
pq  0.24984398691613768

 15
pq  0.6359953812447166
pq  0.44578268674743377

 16
pq  0.8300150826092793
pq  0.0

 17
pq  0.7468902648025428
pq  0.5701052500005701

 18
pq  0.7134255404445696
pq  0.3698057243771012

 19
pq  0.81

In [6]:
! python run.py --true_path={true_path} --pred_path={true_path} --save_path={save_path} --type_path={true_tissue_path}

arguments extracted! 
all loaded!

 0
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
pq bin: 0.9999999473684238
pq  0.9999999444444475
pq  0.9999990000010001

 1
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
pq bin: 0.9999999729729737
pq  0.9999999615384629
pq  0.9999999090909174

 2
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
pq bin: 0.9999999795918372
pq  0.9999995

In [7]:
! python run.py --true_path={pred_path} --pred_path={pred_path} --save_path={save_path} --type_path={true_tissue_path}

arguments extracted! 
all loaded!

 0
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
pq bin: 0.9999999375000038
pq  0.9999999285714337
pq  0.9999990000010001
pq  0.9999990000010001

 1
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33]
pq bin: 0.9999999696969707
pq  0.9999999655172426
pq  0.9999997500000625

 2
pred bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
true bin(int32): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
pq bin: 0.9999999772727278
pq  0.9999998571428775
pq  0.9999997500000625
pq  0.999999969696

In [8]:
import glob as glob
import os

In [9]:
pred_dir = "../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold3Tr_fold2Val_amp/net_epoch49/RTS_softmax/hor_ver_rot90_90_mult_gauNoi_gauBlur/mat/"

gt_dir = "../../../DATASETS/fold1/Labels/"
pred_files = os.listdir(pred_dir)

In [15]:
pred_dir = '../../outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold1Tr_fold2Val_amp/net_epoch48/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/mat/'
gt_dir = '../../../DATASETS/fold3/Labels/'
pred_files = os.listdir(pred_dir)
gt_files = os.listdir(gt_dir)


In [36]:
pred_dir = '../..//outputs/FinalResults/Pannuke/tp_preact-CBAM-ECA_k7_pannuke_fold2Tr_fold1Val_amp/net_epoch41/RTS/hor_ver_rot90_90_mult_gauNoi_gauBlur/mat/'
gt_dir = '../../../DATASETS/fold3/Labels/'

pred_files = os.listdir(pred_dir)
gt_files = os.listdir(gt_dir)

In [37]:
len(gt_files), len(os.listdir(pred_dir))

(2723, 2722)

In [27]:
len(glob.glob(pred_dir+'*.mat'))

2716

In [28]:
gt_files[1][:-3]

'f3_Esophagus_image1068.'

In [29]:
to_move = []
for fi in os.listdir(gt_dir):
#     print(fi)
    if fi not in pred_files:
        if fi[0] != '.':
            print(fi)
            to_move.append(fi[:-3]+'npy')

f3_Breast_image187.mat
f3_Breast_image600.mat
f3_Ovarian_image2301.mat
f3_Colon_image1816.mat
f3_Uterus_image2613.mat
f3_Esophagus_image1964.mat


In [30]:
import shutil
import numpy as np

In [23]:
gt_images = '../../../DATASETS/fold1/images/'
gt_moved = '../../../DATASETS/fold1/moved/'


In [31]:
gt_images = '../../../DATASETS/fold3/images/'
gt_moved = '../../../DATASETS/fold3/moved_images/'


In [32]:
for fi in to_move:
    shutil.copy(gt_images+fi, gt_moved)

In [33]:
for fi in glob.glob(gt_moved+"*.npy"):
    img = np.load(fi)
    print(fi, img.shape)

../../../DATASETS/fold3/moved_images/f3_Breast_image600.npy (256, 256, 3)
../../../DATASETS/fold3/moved_images/f3_Breast_image187.npy (256, 256, 3)
../../../DATASETS/fold3/moved_images/f3_Ovarian_image2301.npy (256, 256, 3)
../../../DATASETS/fold3/moved_images/f3_Uterus_image2613.npy (256, 256, 3)
../../../DATASETS/fold3/moved_images/f3_Colon_image1816.npy (256, 256, 3)
../../../DATASETS/fold3/moved_images/f3_Esophagus_image1964.npy (256, 256, 3)


In [5]:
!pwd

/home/nimra_amin/WORKSPACE/JupyterLab/nucleiDetectClassify/hover_net/metrics/pannuke


In [3]:
import numpy as np

In [5]:
pred = np.load(pred_path)
pred.shape

(2642, 256, 256, 5)

In [6]:
np.unique(pred)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [4]:
true = np.load('../../../DATASETS/fold1/metrics/masks_fold1.npy')
true.shape

FileNotFoundError: [Errno 2] No such file or directory: '../../../DATASETS/fold1/metrics/masks_fold1.npy'

In [8]:
np.unique(true)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [14]:
mk = np.load('../../../DATASETS/PanNuke/fold1/masks.npy')

In [15]:
mk.shape

(2656, 256, 256, 6)

In [16]:
np.unique(mk[:5])

array([  0.,   1.,   3.,   4.,   6.,   8.,   9.,  10.,  11.,  14.,  15.,
        17.,  18.,  19.,  21.,  22.,  23.,  24.,  26.,  27.,  28.,  29.,
        30.,  31.,  33.,  34.,  35.,  36.,  38.,  39.,  40.,  41.,  42.,
        43.,  46.,  48.,  49.,  58.,  60.,  64.,  70.,  81.,  82., 156.,
       159.])